### ISSUE TITLE
Too big & Errors

### ISSUE THREAD

**Issue by tuck0066** [tuck0066/fancy-hover-boxes#1]
@mackenzierose @hellachella

Hi!  I am not sure if we are supposed to edit the pictures or not but mine are HUGE.  I am getting transition errors and I am not sure why.  Thomas' bottom code confused me so I am not sure if I was supposed to remove code or what.  Other then big they seem to work right.

![Screenshot (763)](https://user-images.githubusercontent.com/70998021/98795025-bcf44d00-23d7-11eb-86a4-de2c26cfdda6.png)
![Screenshot (762)](https://user-images.githubusercontent.com/70998021/98795026-bd8ce380-23d7-11eb-9f72-6860adf784bc.png)

**Comment by MacKenzieRose** [comment]
Hi Keri-Lynn~

The only thing your code is missing to fix the image sizing is:

`img {`
  `display: block;`
  `width: 100%;`
`}`

Hope that helps~

**Comment by tuck0066** [comment]
Thanks MacKenzie that did the trick on the sizing issue.  Still getting those other errors but I think it is a me and markbot issue again.  Here are the latest screenshots.  
![Screenshot (766)](https://user-images.githubusercontent.com/70998021/98841709-82f66b80-2416-11eb-9836-7b9b1cbd10bc.png)
![Screenshot (765)](https://user-images.githubusercontent.com/70998021/98841711-82f66b80-2416-11eb-9a63-68b31cb870c1.png)

**Comment by MacKenzieRose** [comment]
To fix the leading zero errors, change numbers like 0.5 to just **.5** (remove the zero);

For empty lines, just make sure that you delete extra horizontal empty space

#### Wrong:
>Some code here 
> `
> `
> `
> `
> `
> `
>More code here

#### Right:
>Some code here 
> `
> `
>More code here

**Comment by tuck0066** [comment]
Fixed the zeros and it was happy with that.  I can't seem to find the error for the spacing.  It is   margin: 0; with two spaces at the front and none at the back.  I can't see any other spaces but I tend to be a little blind.

**Comment by tuck0066** [comment]
Opps!  I was looking in the CSS file for the error not the index.  WOOOT!  You are awesome!  Markbot loves me and it is submitted.
